pipeline{
    agent any
    stages{
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps{
                powershell "git clone https://github.com/sabbir-ul-alam/playwright-automation-python.git"
            }
        }
        stage("Install dependencies"){
            steps{
                dir("playwright-automation-python"){
                    catchError(Error: 'The current project could not be installed'){
                    powershell 'poetry install'
                    powershell 'poetry run playwright install'
                    powershell '''
                    $venv = poetry env activate
                    invoke-Expression $venv
                    '''
                    }
                }
            }
        }
        stage("Tests"){
            steps{
                dir("playwright-automation-python"){
                    powershell 'pytest .\tests\test_contactus.py -v --reruns 2'
                }
            }
        }
    }
}